// <auto-generated />
using System;
using DotNetProjectBackEnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetProjectBackEnd.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190506011815_DotNetProjectBackend.Model.ApplicationContext")]
    partial class DotNetProjectBackendModelApplicationContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetProjectBackEnd.Models.Amenities", b =>
                {
                    b.Property<long>("AmenitiesID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amenity");

                    b.Property<string>("RoomType");

                    b.HasKey("AmenitiesID");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("DotNetProjectBackEnd.Models.Booking", b =>
                {
                    b.Property<long>("Booking_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BookingDate");

                    b.Property<DateTime>("Check_In_Date");

                    b.Property<DateTime>("Check_Out_Date");

                    b.Property<long>("Customer_ID");

                    b.Property<long>("Guest_ID");

                    b.Property<int>("No_Of_Persons");

                    b.Property<int>("No_Of_Rooms");

                    b.Property<double>("Price");

                    b.Property<int>("PromoID");

                    b.Property<int>("Refundable");

                    b.Property<int>("Room_Type");

                    b.Property<double>("Total_Price");

                    b.HasKey("Booking_Id");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("DotNetProjectBackEnd.Models.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateOfRegistration");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DotNetProjectBackEnd.Models.Option", b =>
                {
                    b.Property<int>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Breakfast");

                    b.Property<string>("Deal");

                    b.Property<double>("DiscountedPrice");

                    b.Property<string>("Included");

                    b.Property<int>("NonRefundable");

                    b.Property<string>("OptionName");

                    b.Property<string>("PromoID");

                    b.Property<double>("RealPrice");

                    b.Property<int>("Recommended");

                    b.HasKey("OptionID");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("DotNetProjectBackEnd.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardNumber");

                    b.Property<string>("CardType");

                    b.Property<int>("ExpiryMonth");

                    b.Property<int>("ExpiryYear");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("NameOnCard");

                    b.Property<long>("PriceAfterDiscount");

                    b.Property<long>("PriceBeforeDiscount");

                    b.Property<long>("TotalDiscount");

                    b.HasKey("PaymentId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("DotNetProjectBackEnd.Models.Promo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Discount");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Promo");
                });

            modelBuilder.Entity("DotNetProjectBackEnd.Models.Review", b =>
                {
                    b.Property<long>("ReviewerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Feedback");

                    b.Property<int>("Rating");

                    b.Property<string>("Reviewer");

                    b.Property<string>("Title");

                    b.HasKey("ReviewerID");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("DotNetProjectBackEnd.Models.Room", b =>
                {
                    b.Property<long>("RoomNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OptionID");

                    b.Property<int>("RoomTypeID");

                    b.Property<int>("Status");

                    b.HasKey("RoomNumber");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("DotNetProjectBackEnd.Models.RoomType", b =>
                {
                    b.Property<int>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoomTypeName");

                    b.HasKey("RoomTypeID");

                    b.ToTable("RoomType");
                });

            modelBuilder.Entity("DotNetProjectBackEnd.Models.Traveller", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Traveller");
                });
#pragma warning restore 612, 618
        }
    }
}
